version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: insurance-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: insurance_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./api
    container_name: insurance-api
    restart: always
    environment:
      DATABASE_URL: "mysql+pymysql://root:root123@db:3306/insurance_db"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
